#Configurations for myAppEngine

# deploymentPath : This the path where all the apps will be placed in separate directories along with configurations
deploymentPath: ./bin/deployments
logPath:  ./bin/data/log
